version: '3.3'

services:
   phpfpm:
     image: php-fpm
     user: www-data
     build:
       context: .
       dockerfile: docker/Dockerfile-phpfpm
 
     # environment:
     #   - foo=bar
     ports:
       # the actual fpm port
       - 9000:9000
       # fpm monitoring
       - 9191:9191
     tty: true
     stdin_open: true
     depends_on:
       - db
     volumes:
       - "./wordpress:/var/www"

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   nginx:
    image: nginx:alpine
    ports:
      - 80:80
      # - 443:443
    depends_on:
      - phpfpm
      - db
    volumes:
      - "./wordpress:/var/www"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx.app.conf:/etc/nginx/conf.d/default.conf"

   cli:
     image: php-fpm
     user: www-data
     working_dir: "/var/www/"
     env_file:
       - ./.env
     environment:
       - HOME=/tmp
     # depends_on:
     #   - db
     links:
       - db:mysql
     volumes:
       - "./scripts:/var/www/scripts"
       - "./wp-cli.yml:/var/www/wp-cli.yml"
       - "./wordpress:/var/www/wordpress"
       - "./premium-plugins:/var/www/premium-plugins"
       - "./docker/nginx.conf:/etc/nginx/nginx.conf"
       - "./docker/nginx.app.conf:/etc/nginx/conf.d/default.conf"

   # wordpress:
   #   restart: always
   #   build: docker/php7xml/
   #   working_dir: "/var/www/html/"
   #   environment:
   #     - "PATH=/var/www/html/bin:$PATH"
   #   volumes:
   #     - ".:/var/www/html"
   #     - "./log:/var/log/apache2"
   #     - "./docker/confs:/etc/my_confs/"
   #     - "./docker/run_first.sh:/etc/my_runalways/run_first.sh"
   #   ports:
   #     - "80:80"
   #     - "8765:8765"
   #   depends_on:
   #     - db

volumes:
    db_data: {}


