# php-fpm
FROM php:7.3-fpm-alpine

# Drupal has some needs
#  - php gd
RUN apk add --no-cache freetype libpng libjpeg-turbo mysql-client freetype-dev libpng-dev libjpeg-turbo-dev && \
  docker-php-ext-configure gd \
    --with-gd \
    --with-freetype-dir=/usr/include/ \
    --with-png-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ && \
  NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
  docker-php-ext-install -j${NPROC} gd && \
  apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev

#   - opcache
RUN docker-php-ext-configure opcache --enable-opcache \
    && docker-php-ext-install opcache

RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN cd /tmp && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

RUN curl -L https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/bin/wp && chmod a+x /usr/bin/wp

CMD ["php-fpm"]

RUN mkdir /var/www/wordpress
RUN chown www-data:www-data /var/www
RUN chown www-data:www-data /var/www/wordpress

EXPOSE 9000
